    - name: install mysql
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: system service start
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: change default user password
      ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}